name: Build for macOS
run-name: "Build for macOS: arch ${{ inputs.arch }} | ref ${{ inputs.ref || github.ref_name }}"

on:
    workflow_dispatch:
        inputs:
            arch:
                description: The architecture to build for
                required: true
                default: arm64
                type: choice
                options:
                    - arm64
                    - x64
            ref:
                description:
                    Ref (Tag, branch, commit SHA) to release.
                    Defaults to the ref of the workflow.
                type: string
    workflow_call:
        inputs:
            arch:
                required: true
                default: arm64
                type: string
            ref:
                description: Ref to build from
                type: string

jobs:
    build:
        name: Build macOS ${{ inputs.arch }}
        # For arm64 use macos-latest, for x64 use macos-15-intel (See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#choosing-github-hosted-runners)
        runs-on: ${{ inputs.arch == 'arm64' && 'macos-latest' || 'macos-15-intel' }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}

            - name: Build
              uses: ./.github/actions/build-action

            - name: Fetch certificate file
              env:
                  NORDIC_SIGNING_CERTIFICATE:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_P12 }}
              run:
                  echo "$NORDIC_SIGNING_CERTIFICATE" | base64 --decode >
                  ./nordic_signing_certificate.p12
              if: github.event_name != 'pull_request'

            - name: Run Electron Builder
              env:
                  CSC_LINK: ./nordic_signing_certificate.p12
                  CSC_KEY_PASSWORD:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_P12_PASS }}
                  APPLE_ID: ${{ secrets.WAYLAND_APPLE_ID }}
                  APPLE_APP_SPECIFIC_PASSWORD:
                      ${{ secrets.WAYLAND_APPLE_APP_SPECIFIC_PASS }}
                  APPLE_TEAM_ID: ${{ secrets.WAYLAND_APPLE_TEAMID }}
              run: npx electron-builder -p never --${{ inputs.arch }}
              if: github.event_name != 'pull_request'

            - name: Upload
              uses: ./.github/actions/publish-action
              with:
                  suffix: macOS-${{ inputs.arch }}
              if: github.event_name != 'pull_request'
