name: Continue production release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: Tag of the release to continue.
                type: string
                required: true

jobs:
    check-version:
        name: Check version and existence
        runs-on: ubuntu-latest
        steps:
            - name: Check version and existence
              id: check
              env:
                  GH_TOKEN: ${{ github.token }}
                  TAG: ${{ inputs.tag }}
              run: |
                  # Check if this is a release version (not RC)
                  if [[ "$TAG" == *-rc* ]]; then
                      echo "::error::Not running because $TAG is a release candidate version"
                      exit 1
                  fi

                  # Check if GitHub release already exists
                  if ! gh release view "$TAG" --repo nordicsemiconductor/pc-nrfconnect-launcher >/dev/null 2>&1; then
                      echo "::error::Not running because there is no GitHub release with the tag $TAG prepared yet"
                      exit 1
                  fi

                  # Check if Artifactory release already exists
                  ARTIFACTORY_URL="https://files.nordicsemi.com/artifactory/swtools/external/ncd/launcher/$TAG"
                  if curl --head --fail "$ARTIFACTORY_URL" >/dev/null 2>&1; then
                      echo "::error::Not running because an Artifactory release with version $TAG already exists"
                      exit 1
                  fi

    continue-release:
        name: Continue production release
        needs: check-version
        uses: ./.github/workflows/continue-release-common.yml
        with:
            release-type: production
            tag: ${{ inputs.tag }}
        secrets: inherit

    copy-to-web-assets:
        name: Copy to web-assets to show the release on nordicsemi.com
        needs: [check-version, continue-release]
        runs-on: ubuntu-latest
        env:
            TAG: ${{ inputs.tag }}
        steps:
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env:
                  JF_URL: https://files.nordicsemi.com/
                  JF_ACCESS_TOKEN:
                      ${{ secrets.COM_NORDICSEMI_FILES_PASSWORD_SWTOOLS_FRONTEND
                      }}

            - name: Copy to web-assets
              run: |
                  jf rt copy --flat "swtools/external/ncd/launcher/$TAG/" web-assets-com_nordicsemi/external/swtools/ncd/launcher/$TAG/
                  jf rt copy --flat "swtools/external/ncd/launcher/latest*" web-assets-com_nordicsemi/external/swtools/ncd/launcher/

    publish-docs:
        uses: ./.github/workflows/docs-publish-prod.yml
        with:
            ref: ${{ inputs.tag }}
        needs: continue-release
        secrets: inherit
